# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 06:49
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=app.models.accessories_file)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('delivery_statement', models.CharField(choices=[('W', 'Everywhere in the world'), ('C', 'Only in your base country'), ('CI', 'Only in your base city')], default='CI', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dp', models.ImageField(upload_to=app.models.dp_file)),
                ('cover_photo', models.ImageField(upload_to=app.models.covers_file)),
                ('city', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('bio', models.TextField(default="We are a fashion company based in Lagos, we specialize in all African Attires and our customer's smile are a proof of our competency")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='FabricCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Designer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fabrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=app.models.fabrics_file)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to=app.models.fabrics_file)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FabricCollection')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='app.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tummy', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('top_half_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('top_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('long_sleeve', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('short_sleeve', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('round_sleeve', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('arm_hole', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('handcuff', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bum', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('lap', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ankle', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('knee_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('trouser_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('flab', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('responsiveness', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('delivery_time', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('quality', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('comment', models.TextField()),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='27TDRF', max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('custom_price', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=app.models.styles_file)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to=app.models.styles_file)),
                ('photo3', models.ImageField(blank=True, null=True, upload_to=app.models.styles_file)),
                ('photo4', models.ImageField(blank=True, null=True, upload_to=app.models.styles_file)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='app.Category')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='app.Designer')),
                ('fabricCollection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FabricCollection')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Unsuccessful', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('R', 'Order received by Designer'), ('F', 'Gotten the Fabric'), ('S', 'Currently been sown'), ('D', 'To be delivered today')], default='R', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('reference', models.CharField(max_length=50)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.Transactions')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessories',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='app.Designer'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='accessories',
            field=models.ManyToManyField(to='app.Accessories'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Designer'),
        ),
        migrations.AddField(
            model_name='order',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fabrics'),
        ),
        migrations.AddField(
            model_name='order',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Styles'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order'),
        ),
    ]
