# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 20:27
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_styles_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.styles_file),
        ),
        migrations.AddField(
            model_name='styles',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.styles_file),
        ),
        migrations.AddField(
            model_name='styles',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.styles_file),
        ),
        migrations.AddField(
            model_name='styles',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.styles_file),
        ),
    ]
