# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:15
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170702_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrics',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.fabrics_file),
        ),
        migrations.AddField(
            model_name='fabrics',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.fabrics_file),
        ),
    ]
