# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170702_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styles',
            old_name='styles',
            new_name='fabrics',
        ),
    ]
